services:
  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_DB: "config"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - /home/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - balancer-net
  back1:
    image: backend-server
    build:
      context: ./backends
    container_name: backend-server-1
    networks:
      - balancer-net

  back2:
    image: backend-server
    build:
      context: ./backends
    container_name: backend-server-2
    networks:
      - balancer-net

  load-balancer:
    image: load-balancer
    build:
      context: balancer
    container_name: load-balancer
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - balancer-net
    ports:
      - "8080:8080"

volumes:
  pgdata:
    driver: local

networks:
  balancer-net:
    driver: bridge