port: "8080"
backend-servers:
  - "http://backend-server-1:8080"
  - "http://backend-server-2:8080"
db:
  url: postgres://postgres:postgres@postgresdb:5432/config
rate-limiter:
  capacity: 10
  refill-interval: "5s"